<script lang="ts">
  import { progressStore } from '../stores/progressStore';
  import type { ApplicationFormData } from '../types';

  let formData: Partial<ApplicationFormData> = $progressStore.formData || {};

  // Auto-save to store when form data changes
  $: {
    progressStore.updateFormData(formData);
  }

  function generateDocument() {
    // Generate a formatted text document
    const doc = `
═══════════════════════════════════════════════════════════════
        APPLICATION FOR TEMPORARY RESIDENCE PERMIT (RVP)
                      Under RVP702 Program
═══════════════════════════════════════════════════════════════

PERSONAL INFORMATION
────────────────────────────────────────────────────────────────
Last Name:           ${formData.lastName || '[Not provided]'}
First Name:          ${formData.firstName || '[Not provided]'}
Middle Name:         ${formData.middleName || '[Not provided]'}
Date of Birth:       ${formData.dateOfBirth || '[Not provided]'}
Place of Birth:      ${formData.placeOfBirth || '[Not provided]'}
Citizenship:         ${formData.citizenship || '[Not provided]'}
Gender:              ${formData.gender ? formData.gender.toUpperCase() : '[Not provided]'}

CURRENT ADDRESS (Home Country)
────────────────────────────────────────────────────────────────
Address:             ${formData.currentAddress || '[Not provided]'}
City:                ${formData.currentCity || '[Not provided]'}
Country:             ${formData.currentCountry || '[Not provided]'}

RUSSIAN ADDRESS
────────────────────────────────────────────────────────────────
Address:             ${formData.russianAddress || '[Not provided]'}
City:                ${formData.russianCity || '[Not provided]'}
Region:              ${formData.russianRegion || '[Not provided]'}

PASSPORT INFORMATION
────────────────────────────────────────────────────────────────
Passport Number:     ${formData.passportNumber || '[Not provided]'}
Issue Date:          ${formData.passportIssueDate || '[Not provided]'}
Expiry Date:         ${formData.passportExpiryDate || '[Not provided]'}

VISA INFORMATION
────────────────────────────────────────────────────────────────
Visa Number:         ${formData.visaNumber || '[Not provided]'}
Issue Date:          ${formData.visaIssueDate || '[Not provided]'}
Entry Date:          ${formData.entryDate || '[Not provided]'}

CONTACT INFORMATION
────────────────────────────────────────────────────────────────
Phone Number:        ${formData.phoneNumber || '[Not provided]'}
Email:               ${formData.email || '[Not provided]'}

TAX & IDENTIFICATION
────────────────────────────────────────────────────────────────
INN (Tax Number):    ${formData.inn || '[Not provided]'}

EMPLOYMENT/STUDY INFORMATION
────────────────────────────────────────────────────────────────
Occupation:          ${formData.occupation || '[Not provided]'}
Employer/Institution: ${formData.employer || '[Not provided]'}

REASON FOR RVP APPLICATION
────────────────────────────────────────────────────────────────
${formData.rvpReason || '[Not provided]'}

═══════════════════════════════════════════════════════════════
Generated on: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}
Generated by: RVP702 Guide Application
═══════════════════════════════════════════════════════════════

NOTE: This is a draft document for your reference. Please verify
all information with the official Russian migration authorities
and use their official forms for submission.
    `.trim();

    // Create and download the document
    const blob = new Blob([doc], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `RVP_Application_${formData.lastName || 'Draft'}_${new Date().getTime()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  function clearForm() {
    if (confirm('Are you sure you want to clear all form data?')) {
      formData = {};
      progressStore.updateFormData({});
    }
  }
</script>

<div class="application-form">
  <div class="form-header">
    <h2>RVP Application Form</h2>
    <p>Comming soon</p>
  </div>

  <!-- <form on:submit|preventDefault={generateDocument}>
    <div class="form-section">
      <h3>Personal Information</h3>
      <div class="form-grid">
        <div class="form-field">
          <label for="lastName">Last Name *</label>
          <input type="text" id="lastName" bind:value={formData.lastName} required />
        </div>
        <div class="form-field">
          <label for="firstName">First Name *</label>
          <input type="text" id="firstName" bind:value={formData.firstName} required />
        </div>
        <div class="form-field">
          <label for="middleName">Middle Name</label>
          <input type="text" id="middleName" bind:value={formData.middleName} />
        </div>
        <div class="form-field">
          <label for="dateOfBirth">Date of Birth *</label>
          <input type="date" id="dateOfBirth" bind:value={formData.dateOfBirth} required />
        </div>
        <div class="form-field">
          <label for="placeOfBirth">Place of Birth *</label>
          <input type="text" id="placeOfBirth" bind:value={formData.placeOfBirth} required />
        </div>
        <div class="form-field">
          <label for="citizenship">Citizenship *</label>
          <input type="text" id="citizenship" bind:value={formData.citizenship} required />
        </div>
        <div class="form-field">
          <label for="gender">Gender *</label>
          <select id="gender" bind:value={formData.gender} required>
            <option value="">Select...</option>
            <option value="male">Male</option>
            <option value="female">Female</option>
          </select>
        </div>
      </div>
    </div>

    <div class="form-section">
      <h3>Current Address (Home Country)</h3>
      <div class="form-grid">
        <div class="form-field full-width">
          <label for="currentAddress">Address *</label>
          <input type="text" id="currentAddress" bind:value={formData.currentAddress} required />
        </div>
        <div class="form-field">
          <label for="currentCity">City *</label>
          <input type="text" id="currentCity" bind:value={formData.currentCity} required />
        </div>
        <div class="form-field">
          <label for="currentCountry">Country *</label>
          <input type="text" id="currentCountry" bind:value={formData.currentCountry} required />
        </div>
      </div>
    </div>

    <div class="form-section">
      <h3>Russian Address</h3>
      <div class="form-grid">
        <div class="form-field full-width">
          <label for="russianAddress">Address *</label>
          <input type="text" id="russianAddress" bind:value={formData.russianAddress} required />
        </div>
        <div class="form-field">
          <label for="russianCity">City *</label>
          <input type="text" id="russianCity" bind:value={formData.russianCity} required />
        </div>
        <div class="form-field">
          <label for="russianRegion">Region *</label>
          <input type="text" id="russianRegion" bind:value={formData.russianRegion} required />
        </div>
      </div>
    </div>

    <div class="form-section">
      <h3>Passport Information</h3>
      <div class="form-grid">
        <div class="form-field">
          <label for="passportNumber">Passport Number *</label>
          <input type="text" id="passportNumber" bind:value={formData.passportNumber} required />
        </div>
        <div class="form-field">
          <label for="passportIssueDate">Issue Date *</label>
          <input type="date" id="passportIssueDate" bind:value={formData.passportIssueDate} required />
        </div>
        <div class="form-field">
          <label for="passportExpiryDate">Expiry Date *</label>
          <input type="date" id="passportExpiryDate" bind:value={formData.passportExpiryDate} required />
        </div>
      </div>
    </div>

    <div class="form-section">
      <h3>Visa Information</h3>
      <div class="form-grid">
        <div class="form-field">
          <label for="visaNumber">Visa Number *</label>
          <input type="text" id="visaNumber" bind:value={formData.visaNumber} required />
        </div>
        <div class="form-field">
          <label for="visaIssueDate">Issue Date *</label>
          <input type="date" id="visaIssueDate" bind:value={formData.visaIssueDate} required />
        </div>
        <div class="form-field">
          <label for="entryDate">Entry Date to Russia *</label>
          <input type="date" id="entryDate" bind:value={formData.entryDate} required />
        </div>
      </div>
    </div>

    <div class="form-section">
      <h3>Contact Information</h3>
      <div class="form-grid">
        <div class="form-field">
          <label for="phoneNumber">Phone Number</label>
          <input type="tel" id="phoneNumber" bind:value={formData.phoneNumber} />
        </div>
        <div class="form-field">
          <label for="email">Email</label>
          <input type="email" id="email" bind:value={formData.email} />
        </div>
        <div class="form-field">
          <label for="inn">INN (Tax Number)</label>
          <input type="text" id="inn" bind:value={formData.inn} />
        </div>
      </div>
    </div>

    <div class="form-section">
      <h3>Employment/Study Information</h3>
      <div class="form-grid">
        <div class="form-field">
          <label for="occupation">Occupation</label>
          <input type="text" id="occupation" bind:value={formData.occupation} />
        </div>
        <div class="form-field">
          <label for="employer">Employer/Institution</label>
          <input type="text" id="employer" bind:value={formData.employer} />
        </div>
      </div>
    </div>

    <div class="form-section">
      <h3>Reason for RVP Application</h3>
      <div class="form-field full-width">
        <label for="rvpReason">Explain your reason for applying *</label>
        <textarea
          id="rvpReason"
          bind:value={formData.rvpReason}
          rows="4"
          required
          placeholder="e.g., Employment, Family reunification, Study, etc."
        ></textarea>
      </div>
    </div>

    <div class="form-actions">
      <button type="submit" class="generate-btn">📄 Generate Document</button>
      <button type="button" class="clear-btn" on:click={clearForm}>🗑️ Clear Form</button>
    </div>

    <div class="form-notice">
      <p>
        ⚠️ <strong>Important:</strong> This generated document is for reference only. Always use
        official forms provided by Russian migration authorities for your actual application.
      </p>
    </div>
  </form> -->
</div>

<style>
  .application-form {
    max-width: 900px;
    margin: 0 auto;
  }

  .form-header {
    background: white;
    padding: 1.5rem;
    border-radius: 8px;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
    margin-bottom: 1.5rem;
    border-left: 4px solid #0039a6;
  }

  .form-header h2 {
    color: #333;
    margin-bottom: 0.5rem;
    font-size: 1.5rem;
    font-weight: 600;
  }

  .form-header p {
    color: #555;
    font-size: 0.95rem;
    margin: 0;
  }

  form {
    background: white;
    padding: 1.5rem;
    border-radius: 8px;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);
    border: 2px solid #e0e0e0;
  }

  .form-section {
    margin-bottom: 1.5rem;
    padding-bottom: 1.5rem;
    border-bottom: 1px solid #e0e0e0;
  }

  .form-section:last-of-type {
    border-bottom: none;
  }

  .form-section h3 {
    color: #333;
    margin-bottom: 1rem;
    font-size: 1rem;
    font-weight: 600;
  }

  .form-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 1rem;
  }

  .form-field {
    display: flex;
    flex-direction: column;
  }

  .form-field.full-width {
    grid-column: 1 / -1;
  }

  label {
    color: #333;
    font-weight: 500;
    margin-bottom: 0.4rem;
    font-size: 0.85rem;
  }

  input,
  select,
  textarea {
    padding: 0.6rem 0.75rem;
    border: 2px solid #e0e0e0;
    border-radius: 6px;
    font-size: 0.9rem;
    font-family: inherit;
    transition: border-color 0.2s;
  }

  input:focus,
  select:focus,
  textarea:focus {
    outline: none;
    border-color: #0039a6;
  }

  textarea {
    resize: vertical;
    min-height: 100px;
  }

  .form-actions {
    display: flex;
    gap: 1rem;
    margin-top: 1.5rem;
  }

  .generate-btn,
  .clear-btn {
    padding: 0.75rem 1.5rem;
    border: none;
    border-radius: 6px;
    font-size: 0.9rem;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s;
  }

  .generate-btn {
    background: #4caf50;
    color: white;
    flex: 1;
  }

  .generate-btn:hover {
    background: #45a049;
    transform: translateY(-2px);
    box-shadow: 0 4px 8px rgba(76, 175, 80, 0.3);
  }

  .clear-btn {
    background: #f44336;
    color: white;
  }

  .clear-btn:hover {
    background: #d32f2f;
    transform: translateY(-2px);
  }

  .form-notice {
    background: #fffcf5;
    border: 2px solid #ffc107;
    border-left: 4px solid #ffc107;
    border-radius: 6px;
    padding: 0.75rem 1rem;
    margin-top: 1.5rem;
  }

  .form-notice p {
    margin: 0;
    color: #856404;
    font-size: 0.85rem;
    line-height: 1.5;
    text-align: left;
  }

  @media (max-width: 768px) {
    .form-grid {
      grid-template-columns: 1fr;
    }

    .form-actions {
      flex-direction: column;
    }

    .generate-btn {
      width: 100%;
    }
  }
</style>
